<?php

namespace Practice\HighchartsBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * SerieDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieDataRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findJsonrepo()
    {
        $qb = $this->createQueryBuilder('D');

        $qb->addOrderBy('D.name', 'ASC');

        $results = $qb->getQuery()->getResult(AbstractQuery::HYDRATE_ARRAY);


        $datas = array();
        array_map(function ($value) use (&$datas) {
            if (!array_key_exists($value["name"], $datas)) {
                 $datas[$value["name"]] = array();
            }
            array_push( $datas[$value["name"]], $value["data"]);

        }, $results);


        $formattedDatas = array();
        array_walk ($datas, function($item, $key) use (&$formattedDatas){
            $formattedDatas[] = array(
                "name" => $key,
                "data" => $item
            );
        });

        return $formattedDatas;
    }
 
}
